
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin?characterEncoding=utf-8
    username: root
    password:
    min-poolsize: 1
    max-poolsize: 10
    connect-timeout-ms: 3000
    validate-timeout-ms: 3000


server:
  port: 8070
